services:

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - "postgres"
    volumes:
      - "./backend:/usr/src/app"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: openresty-nginx
    environment:
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/jwt.lua:/usr/local/openresty/nginx/lua/jwt.lua
    depends_on:
      - "api-backend"

volumes:
  postgres_data:
  mongodb_data: